In [ ]:
================= EDA ========
1) pandas     : Dataframe or data applications
2) numpy      : Numerical python for math operations
3) matplotlip : for plots graphs
4) seaborn    : for plots graphs
5) bokhe      : for plots
6) plotly     : for plots


================ Machine learning ===================
7) scikit learn(sklearn)   : ML models
8) stats                   : statistical models


============ Data retrival from sql scrapping ================
9) sqlite                  : connect with database
10) Beautiful soup         : scrap the data from website
11) websocket              : scrap 


==================== Deep learning / Computer vision ====================
12) tensorflow             : Google
13) Keras                  : DL models 
14) Open                   : Image operation
15) pillow(PIL)            : Image Operation
16) pytorch                : Facebook
17) Pretrained model
     VGG16
     Mobilenet
     RESNET
     RCNN
     MASKRCNN
     FASTERCNN
     YOLO

================ Natural language process ==============
18) NLTK                   : natural language process
19) Scipy
20) Word2vec (How words will convert into vector) :
21) GloVE 
22) Wordcloud


================ Hugging Face ======================
23) Transforms     : BERT 


================ GenAI model ======================
24) OpenAI+Microsoft  : GPT Models
25) Google            : Gemini
26) Amazon            : Q
27) Meta Facebook     : MetaAI
28) Apple             : 


LLAMA
GEMMA
Dalle-E
T5

All are having different different package 


==================LANGCHAIN ==============
29) LangChain  Framwork

==================== Deployment /applications  ==============
30) Flask
31) Streamlit
32) Django

==================== Mlops ======================
33) Mlflow
34) Kubeflow
35) Azure Ai services : azure package 
36) GCP  : GCP packages

**Step-1**

Create a Dataframe


- we will create  a dataframe using list

- we will create a dataframe using dictionary

In [5]:
 import pandas as pd

In [11]:
d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [5]:
type(d1)

pandas.core.frame.DataFrame

**step-2**

provide the data

In [8]:
names=['tarun','surendar','mohith']
pd.DataFrame(names)

0
0     tarun
1  surendar
2    mohith

In [13]:
names=['tarun','surendar','mohith']
age=[20,21,22]
city=['Hyd','ECIL','Blr']
Data=zip(names,age)


In [12]:
names=['tarun','surendar','mohith']
age=[20,21,22]
city=['Hyd','ECIL','Blr']
Data=zip(names,age)
pd.DataFrame(zip(names,age,city))

0   1     2
0     tarun  20   Hyd
1  surendar  21  ECIL
2    mohith  22   Blr

**Step-3 Provide the column names**

In [17]:
names=['tarun','surendar','mohith']
pd.DataFrame(names,
            columns=['Names'])

Names
0     tarun
1  surendar
2    mohith

In [25]:
names=['tarun','surendar','mohith']
pd.DataFrame(zip(names,age),
            columns=['Names','Age'])

Names  Age
0     tarun   20
1  surendar   21
2    mohith   22

In [26]:
names=['tarun','surendar','mohith']
age=[20,21,22]
city=['Hyd','ECIL','Blr']
data=zip(names,age,city)
cols=['Name','Age','City']
pd.DataFrame(data,columns=cols)

Name  Age  City
0     tarun   20   Hyd
1  surendar   21  ECIL
2    mohith   22   Blr

**Step-4**

Providing index



In [29]:
names=['tarun','surendar','mohith']
age=[20,21,22]
city=['Hyd','ECIL','Blr']
data=zip(names,age,city)
ix=['A','B','C']
cols=['Name','Age','City']
pd.DataFrame(data,
             ix,
             columns=cols)

Name  Age  City
A     tarun   20   Hyd
B  surendar   21  ECIL
C    mohith   22   Blr

In [28]:
names=('tarun','surendar','mohith')
age=[20,21,22]
data=zip(names,age)
ix=('Hyd','ECIL','Blr')
cols=['Name','Age']
pd.DataFrame(data,
            ix,
            columns=cols)

Name  Age
Hyd      tarun   20
ECIL  surendar   21
Blr     mohith   22

- create the data

- provide the columns

- 

**Step- 5**

add a new column on existing data frame

In [ ]:
# create a data frame
# name
# age
# city


In [6]:
Names=['raghv','kaleem','rahman']
age=[23,22,20]
city=['Andhar','Hyd','Blr']

- if you want add a new column

- First check how many rows are there

- for example in above dataframe we have 3 rows

- your new column also should have 3 rows

- suppose i want to create a new column : **Salary**

- make a list with 3 value

- salary=[100000,200000,300000]

**syntax**=dataframe[column]=list of value

- salary =[100000,200000,300000]

- df['Salary']='Salary'

In [9]:
Salary=[100000,200000,300000]
df['Salary']=Salary
df

NameError: name 'df' is not defined

**use case-1**

- Create empty data frame frist

- Create 3 list using list comprehens

- list 1=a value from 1 to 10

- list2 = square of 1 to 10

- list3 cube of 1 to 10

- Finally make a dataframe 

In [20]:
import pandas as pd

In [24]:
df2=pd.DataFrame()
list1= [i for i in range (1,11)]
list2= [i*i for i in range(1,11)]
list3= [i*i*i for i in range(1,11)]
pd.DataFrame(zip(list1,list2,list3))

0    1     2
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [26]:
df2=pd.DataFrame()
list1= [i for i in range (1,11)]
list2= [i*i for i in range(1,11)]
list3= [i*i*i for i in range(1,11)]

df2=['Natural'] =l1
df2=['Squre'] =l2
df2=['Cube'] =l3
pd.DataFrame(zip(list1,list2,list3))



SyntaxError: cannot assign to literal (1306391741.py, line 5)

**step-6**

 Updat the already existed column

- Create a new dataframe
  - create a new list  Salary =[1000,2000,3000]
  - 
  - df['S']

  - Create a new column the column name is our choice

- update existing column are same way only

  - here also we need a make a list of value = number of rows

  - while updating the existing colum

  - we need to provise already existed column name only
 
  - df['Z']= list of value

In [ ]:
#dataframe name: df1
# list of values 

**step-7**

Drop the column

In [27]:
# how to check the column
df2.column

AttributeError: 'DataFrame' object has no attribute 'column'

In [ ]:
- If yu want to drop a specific column

- we will use drop method

- we already know about diferent

- Keyword will use with directly

- Methods will usse with Corre

df2.drop()

- Column: which column want to drop 

  - axis =0 means rows

  - axis=1 means 

- inplace: will provide overwrites the dataframe or not

  - inplace =True , this indicates overwrite the dataframe

  - inplace = False , this indicates the modified dataframe will be use when provide new variable for the Opeation

In [ ]:
df2.drop('X')

#we are not providing  asie

In [ ]:
df2.drop('X',axis=1)
# after this in a new cell type df2
# you will see orginal dataframe s
# because we did not provide inplace
# 

**Step-8**

**drop the row**

- drop the column and drop the row both are similar only

- the only difference is axis 

   - axis=0 represnts rows

   - by default axis =0 available

   - whuch means if we provide any value ,it will represnt rows only

In [28]:
## Datafrsme name : df 1
import pandas as pd
df2=pd.DataFrame()
l1= [i for i in range (1,10)]
l2= [i*82 for i in range(1,10)]
l3= [i*83 for i in range(1,10)]

df2['Number'] =l1
df2['Square'] =l2
df2['Cube'] =l3
df2



Number  Square  Cube
0       1      82    83
1       2     164   166
2       3     246   249
3       4     328   332
4       5     410   415
5       6     492   498
6       7     574   581
7       8     656   664
8       9     738   747

In [29]:
df2.drop (4)
# if we run this we get error 
#by default axis=0 whuch represent about rows 
# but 'number ' is a column 
# if you want to drop row , the provide the row index

Number  Square  Cube
0       1      82    83
1       2     164   166
2       3     246   249
3       4     328   332
5       6     492   498
6       7     574   581
7       8     656   664
8       9     738   747

In [30]:
# multiple rows 
# multiple column keep always in alist


In [31]:
df2

Number  Square  Cube
0       1      82    83
1       2     164   166
2       3     246   249
3       4     328   332
4       5     410   415
5       6     492   498
6       7     574   581
7       8     656   664
8       9     738   747

In [32]:
df2.columns[[0,1]]

Index(['Number', 'Square'], dtype='object')

In [33]:
df2.drop([0,1],axis=1)
# [0,1] index
# axis =1 columns
# error


KeyError: '[0, 1] not found in axis'

**step-9**

**How to select the columns**

In [34]:
df2['Number']
# series type
# no column name display
# Wheneven you see this type : series type


0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: Number, dtype: int64

In [35]:
df2[['Square']]

Square
0      82
1     164
2     246
3     328
4     410
5     492
6     574
7     656
8     738

In [36]:
type(df2['Number'])

pandas.core.series.Series

In [37]:
type(df2[['Number']])

pandas.core.frame.DataFrame

In [38]:
df2.Number

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: Number, dtype: int64

- df2['Number']:Series type
- df2[['Number']]: Dataframe type
- df2.number:Series type

In [39]:
cols=['Number','Square']
df2[cols]

Number  Square
0       1      82
1       2     164
2       3     246
3       4     328
4       5     410
5       6     492
6       7     574
7       8     656
8       9     738

In [40]:
df2['Number'].values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

- all values come in array

- array means it is a list of elements only represent using numpy package

- Generally elements present in 4 ways

  - List : Basic representation

  - Numpy array : Array with numpy package 

  - Tensors : Tensorflow package

  - Torch  : Pytorch package

In [44]:
list1=[1,2,3,4]
list1

[1, 2, 3, 4]

In [48]:
list2=[10,20,30,40]
list2

[10, 20, 30, 40]

In [45]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [46]:
tensor([1,2,3,4])

NameError: name 'tensor' is not defined

In [49]:
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [50]:
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44])

In [51]:
# 3days every day one hour numpy 
# A new package in the market : numpy
# you know python
#

# Sir what happend about Azure AI certification : August will start
#Offline


In [54]:
df2['Number'].values
# Imagine we worked on an ml problem
# we got some series of value 
# with that series of  value 
# with that series of values also we can create a dataframe

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [53]:
df2['NUMBER']=df2['Number'].values
df2

Number  Square  Cube  NUMBER
0       1      82    83       1
1       2     164   166       2
2       3     246   249       3
3       4     328   332       4
4       5     410   415       5
5       6     492   498       6
6       7     574   581       7
7       8     656   664       8
8       9     738   747       9

**Step-10**

**Save the dataframe**

- Dataframe we can save in two formats

  - csv : comma seprated value

  - xlsx : execl format

- In order to save any data

  - Where you want to save : directory name

  - What is the name of the file for storing 

  - what is the extension

- we already seen same in file handing session

In [ ]:
# case-1 Saving file at same location wher this pythom file 
# no need to provide directory path
# import osd
# Directly give only name of the file
# and extension

In [58]:

# Dataframe name : df2
df2.to_csv('Data1.csv')
df2.to_excel('Data1.xlsx')

**Step-11**

**How to read a dataframe**



In [59]:
import  pandas as  pd 
pd.read_csv('Data1.csv')

Unnamed: 0  Number  Square  Cube  NUMBER
0           0       1      82    83       1
1           1       2     164   166       2
2           2       3     246   249       3
3           3       4     328   332       4
4           4       5     410   415       5
5           5       6     492   498       6
6           6       7     574   581       7
7           7       8     656   664       8
8           8       9     738   747       9

In [60]:
import  pandas as  pd 
pd.read_excel('Data1.xlsx')

Unnamed: 0  Number  Square  Cube  NUMBER
0           0       1      82    83       1
1           1       2     164   166       2
2           2       3     246   249       3
3           3       4     328   332       4
4           4       5     410   415       5
5           5       6     492   498       6
6           6       7     574   581       7
7           7       8     656   664       8
8           8       9     738   747       9

**Step-12**

**How to avoid index column**

- while we save the dataframe 

- autpmatically a new column will create

- that we need to aviod 

- permission denied means close the data file from laptop

In [61]:
# dataframe name : df2
# save the data without  extra index column 
df2.to_csv('Data1.csv',index=False)
df2.to_excel('Data1.xlsx',index=False)

In [62]:
pd.read_csv('Data1.csv')
# read the data


Number  Square  Cube  NUMBER
0       1      82    83       1
1       2     164   166       2
2       3     246   249       3
3       4     328   332       4
4       5     410   415       5
5       6     492   498       6
6       7     574   581       7
7       8     656   664       8
8       9     738   747       9

In [63]:
pd.read_excel('Data1.xlsx')

Number  Square  Cube  NUMBER
0       1      82    83       1
1       2     164   166       2
2       3     246   249       3
3       4     328   332       4
4       5     410   415       5
5       6     492   498       6
6       7     574   581       7
7       8     656   664       8
8       9     738   747       9